server:
  port: 8008
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/chungfung/spring-cloud-config-test
          username: XXXXX
          password: XXXXXXXXX
      name: chungfung